FIRMWARE_MAJOR = 1
FIRMWARE_MINOR = 5
FIRMWARE_PATCH = 1
PROTOCOL_VERSION = 2
MANUFACTURE_ID = "AAA"
CERTIFICATE_PATH = "certs/isrgrootx1.pem"
TEST_API_URL = "https://staging.api.luftdaten.at/v1/station"
API_URL = "https://api.luftdaten.at/v1/station"
UPDATE_SERVER = "https://update.luftdaten.at"
TEST_UPDATE_SERVER = "https://staging.update.luftdaten.at"
DATAHUB_API_URL = "https://datahub.luftdaten.at/api/v1/devices"
DATAHUB_TEST_API_URL = "https://staging.datahub.luftdaten.at/api/v1/devices"